"""
Safari Time - export the par sheet for the web front-end.

Writes web/gamedata.js: a single global object holding the exact strips,
paytable, paylines and rules from engine/config.py, plus the solved RTP
figures. The browser game reads only this file, so it can never drift from
the model that was simulated.

    python -m engine.export
"""

from __future__ import annotations

import json
import os
import sys
from datetime import date

from . import config as cfg
from . import exact

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.join(os.path.dirname(HERE), "web")

ART_FILES = {
    cfg.J: "j", cfg.Q: "q", cfg.K: "k", cfg.A: "a",
    cfg.GIRAFFE: "giraffe", cfg.ZEBRA: "zebra", cfg.RHINO: "rhino",
    cfg.ELEPHANT: "elephant", cfg.LION: "lion", cfg.WILD: "wild", cfg.AFRICA: "africa",
}


def art_manifest() -> dict:
    """Symbol PNGs actually present in web/assets/symbols - the page loads only these."""
    found = {}
    for sym, name in ART_FILES.items():
        for ext in ("png", "webp", "jpg"):
            rel = f"assets/symbols/{name}.{ext}"
            if os.path.exists(os.path.join(WEB, rel)):
                found[str(sym)] = rel
                break
    return found


def payload(rtp: dict = None) -> dict:
    return {
        "art": art_manifest(),
        "title": "Safari Time",
        "generated": date.today().isoformat(),
        "symbols": {str(i): cfg.SYMBOL_NAMES[i] for i in cfg.SYMBOL_NAMES},
        "ids": {
            "J": cfg.J, "Q": cfg.Q, "K": cfg.K, "A": cfg.A,
            "GIRAFFE": cfg.GIRAFFE, "ZEBRA": cfg.ZEBRA, "RHINO": cfg.RHINO,
            "ELEPHANT": cfg.ELEPHANT, "LION": cfg.LION,
            "WILD": cfg.WILD, "AFRICA": cfg.AFRICA,
        },
        "paySymbols": list(cfg.PAY_SYMBOLS),
        "reels": cfg.REELS,
        "rows": cfg.ROWS,
        "stops": cfg.STOPS,
        "lines": cfg.LINES,
        "paylines": cfg.PAYLINES,
        "payDirection": cfg.PAY_DIRECTION,
        "minChain": cfg.MIN_CHAIN,
        "paytable": {str(s): list(v) for s, v in cfg.PAYTABLE.items()},
        "scatterPay": {str(k): v for k, v in cfg.SCATTER_PAY.items()},
        "freeSpins": {str(k): v for k, v in cfg.FREE_SPINS_AWARD.items()},
        "featureWildReels": list(cfg.FEATURE_WILD_REELS),
        "stickyMode": cfg.STICKY_MODE,
        "retrigger": cfg.RETRIGGER,
        "maxFreeSpins": cfg.MAX_FREE_SPINS,
        "betLevelsCents": cfg.BET_LEVELS_CENTS,
        "maxPayoutCents": cfg.MAX_PAYOUT_CENTS,
        "baseStrips": cfg.BASE_STRIPS,
        "featureStrips": cfg.FEATURE_STRIPS,
        "rtp": rtp or {},
    }


def write(rtp: dict = None) -> str:
    os.makedirs(WEB, exist_ok=True)
    path = os.path.join(WEB, "gamedata.js")
    data = payload(rtp)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("// GENERATED by engine/export.py - do not edit by hand.\n")
        fh.write("// Regenerate with:  python -m engine.export\n")
        fh.write("window.SAFARI_TIME = ")
        fh.write(json.dumps(data, indent=1))
        fh.write(";\n")
    return path


def main(argv: list) -> None:
    base = exact.base_line_math()
    scat = exact.scatter_math()
    rtp = {
        "baseLine": round(base["rtp"], 6),
        "triggerOneIn": round(scat["trigger_one_in"], 2),
    }
    # The feature figure comes from a full run of engine/simulate.py; take it
    # from the command line so a quick export never needs a long simulation.
    if len(argv) >= 2 and argv[0] == "--total":
        rtp["total"] = float(argv[1])
    path = write(rtp)
    print(f"wrote {path}")


if __name__ == "__main__":
    main(sys.argv[1:])
